### PR TITLE
Fix TypedPipe.limit to be correct, if slighly slower

### PR DESCRIPTION
**Pull request by johnynek**
this comes up too often, let's just do the correct thing.

### CODE REVIEW

**Comment by johnynek** [comment]
@avibryant any objections here? Seems like the right thing.

**Comment by ianoc** [comment]
I'd like if we kept the method around in some way shape or form, I use it in analysis for quick map only jobs. SomeNewSource.limit(100).dump in the repl is a super fast command, this will be much slower

**Comment by johnynek** [comment]
Are you sure it will be slower? You only need one reducer and it will send
at most N * Mappers data to the reducers.

Can you do a quick benchmark in the repl to compare
groupAll.bufferedTake(100).values on a source you care about?

On Wed, Jul 15, 2015 at 5:58 PM, ianoc <notifications@github.com> wrote:

> I'd like if we kept the method around in some way shape or form, I use it
> in analysis for quick map only jobs. SomeNewSource.limit(100).dump in the
> repl is a super fast command, this will be much slower
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twitter/scalding/pull/1366#issuecomment-121761862>.
>



-- 
Oscar Boykin :: @posco :: http://twitter.com/posco

**Comment by isnotinvain** [comment]
we *could* add a new method that works the way old limit did.

**Comment by ianoc** [comment]
Buffered take will deserialize all of the data in the mapper, the old limit
won't right? It'll terminate after reading the number of records. I'll run
a test in a few mins to confirm

**Comment by johnynek** [comment]
@ianoc you're right that if we have sources that implement deserialization at the scalding layer (as I think LzoCodec does, for instance) limit would not deserialize whereas this implementation would.

We would need an optimizer that could see that limit commutes with map.

**Comment by ianoc** [comment]
Given the old one is only really faster when you delay deserialization as a result think it makes sense to just merge this.

**Comment by avibryant** [comment]
I'm late here but :+1: @johnynek.

**Pull request merged**
