### PR TITLE
Fix SimpleDateFormat caching by default

### PR DESCRIPTION
**Pull request by johnynek**
SimpleDateFormat is not threadsafe, some tests are failing in a way that might be related here.

### CODE REVIEW

**Comment by rubanm** [comment]
LGTM

**Comment by isnotinvain** [comment]
We could also consider using joda-time, it's pretty similar except a) all of it's objects are thread safe and b) it doesn't let you make some of the common mistakes (like swapping YYYY and yyyy -- joda time renames the confusing one to xxxx). It's basically what java's built in time library should be.

**Comment by Gabriel439** [comment]
Yeah, I'm really surprised that we don't use joda time.  I've never used it personally but I've heard nothing but good things about it.

**Comment by johnynek** [comment]
The reason is to avoid a diamond dependency. You can easily make a
DateParser that uses joda time, but since you don't use user threads almost
ever in Hadoop, this is not compelling outside of testing.

On Thursday, April 30, 2015, Gabriel Gonzalez <notifications@github.com>
wrote:

> Yeah, I'm really surprised that we don't use joda time. I've never used it
> personally but I've heard nothing but good things about it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twitter/scalding/pull/1265#issuecomment-97867507>.
>


-- 
Oscar Boykin :: @posco :: http://twitter.com/posco

**Comment by isnotinvain** [comment]
Is that still true with Execution in the mix?

On Thursday, April 30, 2015, P. Oscar Boykin <notifications@github.com>
wrote:

> The reason is to avoid a diamond dependency. You can easily make a
> DateParser that uses joda time, but since you don't use user threads almost
> ever in Hadoop, this is not compelling outside of testing.
>
> On Thursday, April 30, 2015, Gabriel Gonzalez <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > Yeah, I'm really surprised that we don't use joda time. I've never used
> it
> > personally but I've heard nothing but good things about it.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/twitter/scalding/pull/1265#issuecomment-97867507>.
> >
>
>
> --
> Oscar Boykin :: @posco :: http://twitter.com/posco
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twitter/scalding/pull/1265#issuecomment-97878484>.
>


-- 
Sent from my phone

**Pull request merged**
