### PR TITLE
Because, because... fun, the scala compiler has special naming rules …

### LINKED ISSUE #1528: bug in thrift ordered serialization macros
Got an error:

```
 found   : Option[Boolean]
 required: Option[String]
```

in generated code. Can't see the code in a compiled binary, so not sure what the deal is. Just don't want to forget.

I think we need more tests here to call this a success.

### PR DESCRIPTION
**Pull request by ianoc**
…it appears when there are leading underscores

fixes #1528

/cc @johnynek

### CODE REVIEW

**Comment by johnynek** [comment]
Nice catch. Why the toLowerCase?

**Comment by ianoc** [comment]
We do this to try work out the methods which are the field names for the trait, since they aren't case class accessor, we sort of have a guessing game.

The reason for the toLowerCase is because the compiler does capitalization of the first letter of the field name, except if the leading characters are underscores, then its the first non underscore character it seems.

So to just try sidestep the whole mess I went with the toLowerCase, the risk there becomes i guess of a false positive, but I couldn't manage to figure out how to generate something where it doesn't work that is valid thrift.

**Comment by johnynek** [comment]
Can we add an example with a collision in the upper and lower casing? a and A as fields? Is that allowed?

**Comment by johnynek** [comment]
Could we just call the Scrooge method that is doing this mangling? We already depend on Scrooge, right?

**Comment by ianoc** [comment]
well sorry i mean i you can do it if you put long enough field names to avoid the auto-casing. But if you add them as fields, then they are actually fields... so they will be there anyway. They are just there twice.

**Comment by ianoc** [comment]
Its different mangling, this is the scala compiler mangling, not thrift -> scrooge

**Comment by johnynek** [comment]
Ahh. I see.

Well, this is an improvement for sure. Merge when green.

On Thursday, March 3, 2016, ianoc notifications@github.com wrote:

> Its different mangling, this is the scala compiler mangling, not thrift ->
> scrooge
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/twitter/scalding/pull/1534#issuecomment-192119618.

## 

P. Oscar Boykin, Ph.D. | http://twitter.com/posco | http://pobox.com/~boykin

**Pull request merged**
