### PR TITLE
Try turning on mima

### PR DESCRIPTION
**Pull request by piyushnarang**
Updated the version to 0.17.0 and also seeing if we can trigger this from the run_test script.

### CODE REVIEW

**Comment by johnynek** [comment]
looks like all the builds timed out.

**Comment by ttim** [comment]
I think this PR should be against `0.17.x` branch and for `develop` branch `youngestForwardCompatible` should return null.

Meanwhile I checked locally and mima check passed on current 0.17.x branch.

**Comment by piyushnarang** [comment]
Seems to be stuck on a weird issue:
```
Fetching: listen-3.0.8.gem (100%)
listen's executable "listen" conflicts with sass-listen
Overwrite the executable? [yN]  
```

**Comment by piyushnarang** [comment]
Seems like we're installing this for our microsite setup: https://github.com/twitter/scalding/blob/develop/.travis.yml#L10
```
- rvm use 2.2.3 --install --fuzzy
--
  | - gem update --system
  | - gem install sass
  | - gem install jekyll -v 3.2.1
```

**Comment by piyushnarang** [comment]
@johnynek what do you think of @ttim 's suggestion of only enabling this check in 0.17.x (as we are planning to cut 0.18.0 based off develop anyway and we have a bunch of mima failures here already due to the cascading backend rewrites + memory estimator updates). Flip side of not having this on here is that new PRs that are potentially not compatible and could be easily updated to be compatible won't be caught.

**Comment by johnynek** [comment]
I think develop is already broken with respect to mima, so we really can't turn it on, so I think that's right.

**Comment by piyushnarang** [comment]
Ok, closing this review for now. We can set this up again when we have a 0.18.0 release for develop to compare against.

**Pull request closed without merging**
