### PR TITLE
Reformat code with scalafmt

### PR DESCRIPTION
**Pull request by ttim**
This PR contains two changes:
- uncomment code style check in travis configuration
- apply `scalafmtSbt` and `scalafmtAll`

### CODE REVIEW

**Review by johnynek — APPROVED** [review]
well, I did a spot check, but I didn't read everything...

Given that I trust @ttim and that this should be mechanical, I say merge.

**Comment by ttim** [comment]
@tlazaro @nownikhil are you on board with merging this?

**Review by tlazaro — APPROVED** [review]

**Comment by tlazaro** [comment]
Sounds good to me, also trust my former teammate @ttim :D

**Comment by tlazaro** [comment]
I actually scrolled through all the changes just in case. There are a few docs that had custom formatting a might have gotten a bit garbled, I rather merging this PR and fixing those later.

**Comment by ttim** [comment]
Here is script you can verify my change with:
```
git reset --hard b0ba993ac817e6b1e52126e8b1cfb1054cc00dad~1 && 
  ./sbt "scalafmtSbt" "scalafmtAll" "clean" "scalafmtAll" && 
  git add --all && 
  git commit -m "tmp" && 
  git cherry-pick b0ba993ac817e6b1e52126e8b1cfb1054cc00dad && 
  git show
```

No need to trust me =)

**Pull request merged**
