### PR TITLE
fix incorrect usage of the Project constructor

### PR DESCRIPTION
**Pull request by fommil**
https://github.com/ensime/ensime-sbt/issues/210

@ktonga

Note that your version of sbt is quite old, I recommend upgrading to 0.13.11

### CODE REVIEW

**Comment by fommil** [comment]
failures look unrelated to this change

**Comment by isnotinvain** [comment]
Hmm, those failures don't look like transient ones. I'm not sure why this change triggers them but we'll need to get to the bottom of that.

**Comment by fommil** [comment]
Might be that other sbt plugins were misconfigured.

**Comment by isnotinvain** [comment]
Could be, I don't know too much about sbt unfortunately.

We're open to any suggestions on how to refactor / cleanup the build here (including upgrading).
Out of curiosity, why does scalding's build cause issues in the project you linked? It doesn't consume scalding binaries via maven dependencies?

**Comment by fommil** [comment]
One of our users was wanting to hack on scalding and experienced problems. I'm afraid I don't have time to look into this any further. It seems it would probably take quite some time to understand your intricate build and I only sent a PR because it was low hanging fruit to do so.

**Comment by fommil** [comment]
anyway, since I'll not be continuing this PR ... it seems to fidgety ... I'll close the PR.

**Pull request closed without merging**
