### PR TITLE
Update the build

### PR DESCRIPTION
**Pull request by johnynek**

### CODE REVIEW

**Comment by rubanm** [comment]
LGTM

**Comment by rubanm** [comment]
Looks like this failed because we refer to the Build.scala file in our sbt assembly scripts and also scald.rb

```
The command "scripts/build_assembly_no_test.sh scalding-repl" exited with 2.

0.08s$ scripts/test_repl_tutorial.sh

using TRAVIS_SCALA_VERSION 2.10.6

/home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/open-uri.rb:35:in `initialize': No such file or directory - /home/travis/build/twitter/scalding/project/Build.scala (Errno::ENOENT)

	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/open-uri.rb:35:in `open'

	from /home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/open-uri.rb:35:in `open'

	from /home/travis/build/twitter/scalding/scripts/scald.rb:60:in `<main>'

The command "scripts/test_repl_tutorial.sh" exited with 127.

0.01s$ scripts/build_assembly_no_test.sh scalding-core

sed: can't read project/Build.scala: No such file or directory
```

**Comment by rubanm** [comment]
Fixed and restarted build.

**Comment by ianoc** [comment]
Updated for the parquet cascading change.

one thing before merge presuming green is do we know where the other version of algebird-core is coming from, from my build:
```
[warn] 	* com.twitter:algebird-core_2.11:0.10.0 -> 0.11.0
[warn] 	* org.apache.thrift:libthrift:0.5.0 -> 0.7.0
```

**Comment by ianoc** [comment]
```
[info] com.twitter:algebird-core_2.11:0.10.0 (evicted by: 0.11.0)
[info]   +-com.twitter:chill-algebird_2.11:0.7.1 [S]
[info]   | +-com.twitter:scalding-core_2.11:0.15.1-SNAPSHOT [S]
[info]   | 
[info]   +-com.twitter:scalding-core_2.11:0.15.1-SNAPSHOT [S]
```

That maybe is a bit confusing to parse to me in that it implies i think that scalding-core directly depends on this version which I can't see how it does. But chill-algebird does since we haven't gotten to the bump there

**Comment by johnynek** [comment]
about thrift, shouldn't that be provided maybe? We don't want to bump that, do we?

**Comment by johnynek** [comment]
also need new algebird and bijection, right?

**Comment by ianoc** [comment]
I had honestly presumed you had already done that since i was getting warnings about potential incompatible algebird versions in the build

**Comment by johnynek** [comment]
@ianoc I guess that was transitive from chill

**Comment by ianoc** [comment]
Yeah chill must have been another version back of algebird :/

**Pull request merged**
