### PR TITLE
Never double count stats in Execution

### PR DESCRIPTION
**Pull request by johnynek**
Problem:

`a.zip(b)` naively adds the counters from left and right. This leads to very confusing results since both sides may include the same parent jobs, which means minor refactorings can duplicate counters.

Solution:
Rather than using a monoid on `ExecutionCounters` we note that counters are only created in one place, and that place is serialized. So we keep a `Map[Long, ExecutionCounters]` so we can de-dup the counters by only counting each id once. The API is not changed, but people relying on this bug will obviously be broken. Since the current behaviour makes the counters very difficult to use correctly, I strongly feel this is worth it.

### CODE REVIEW

**Comment by johnynek** [comment]
@rubanm we'd love to publish an RC/snapshot fix for this. Can you review?

**Comment by johnynek** [comment]
Actually, I realized, @jnievelt has a lot of `Execution` experience. Can you review, sir?

**Comment by rubanm** [comment]
@johnynek LGTM! Just published 0.16.1-RC1 last week btw. So this could go in RC2.

**Pull request merged**
