### PR TITLE
Remove weakly typed Source

### PR DESCRIPTION
**Pull request by tglstory**
Addresses https://github.com/twitter/scalding/issues/1247

### CODE REVIEW

**Comment by johnynek** [comment]
I'm +1. @rubanm @isnotinvain @jnievelt are you folks willing to help fix any tests this breaks at Twitter?

**Comment by rubanm** [comment]
I'll run a Twitter sandbox with this change so we know just how many targets it affects (hopefully not many).

**Comment by johnynek** [comment]
@rubanm thanks a ton!

**Comment by rubanm** [comment]
@johnynek 22 failing targets, not too bad. So I think we can fix those.

@tglstory There's one failing test on travis, could you fix that so it's green to merge. Thanks

```
[error] /home/travis/build/twitter/scalding/scalding-core/src/test/scala/com/twitter/scalding/mathematics/Matrix2Test.scala:399: ambiguous implicit values:
[error]  both value UnitSetter in object TupleSetter of type => com.twitter.scalding.TupleSetter[Unit]
[error]  and value CTupleSetter in object TupleSetter of type => com.twitter.scalding.TupleSetter[cascading.tuple.Tuple]
[error]  match expected type com.twitter.scalding.TupleSetter[T]
[error]         .source(Tsv("mat2", ('x2, 'y2, 'v2)), List())
[error]                ^
[error] one error found
[error] (scalding-core/test:compileIncremental) Compilation failed
```

**Comment by tglstory** [comment]
updated test.

**Comment by tglstory** [comment]
is this break expected? I resolved the test mentioned by @rubanm, but apparently travis is still failing.

**Comment by johnynek** [comment]
No, this is not expected. These are probably cases where the lack of type-safety of the Fields API is biting us. Those tests probably need an explicit type parameter added.

Can you run `./sbt scalding-core/test` and see if the tests pass on your machine?

**Comment by tglstory** [comment]
Thanks. I'll run that and update the branch when all the tests are fixed.

**Comment by tglstory** [comment]
The BddDsl had some utilization of the weakly typed source.

**Comment by isnotinvain** [comment]
From a binary compatibility standpoint, shouldn't we deprecate this first and then remove in the release that comes after the next release? At some point we were being very careful with our binary compatibility. Even if this isn't too hard to migrate to at Twitter and Stripe there are other users out there too :p

**Comment by isnotinvain** [comment]
I guess we can also just be accurate with our version numbers and let this trigger a new major release

**Comment by johnynek** [comment]
I am kind of bearish on deprecation.

Seems approximately no one acts on that.

A better model might be: use the old code until you want to do the (tiny) work to upgrade.

So, tiny changes (like < 1% or jobs have a mechanical change), is okay if it keeps many users from hitting bad cases.

Something that hits almost everyone, we should not (maybe ever) change.

**Comment by johnynek** [comment]
I'd be +1 this change if @rubanm is still willing to fix the breakage (that fix can happen without shipping w new scalding, just fix the old tests to point to the right new method).

**Comment by rubanm** [comment]
I have the affected tests fixed in a branch, so we can merge this if there's consensus.

**Comment by johnynek** [comment]
Nice, thanks @rubanm !

I want to merge as that method was dangerous and confusing.

**Comment by jnievelt** [comment]
Yeah +1 I've been bitten by this myself

**Comment by johnynek** [comment]
@isnotinvain want to do the honors?

**Comment by tglstory** [comment]
:joy: happy that this is helpful!

**Comment by isnotinvain** [comment]
Sorry, was out of town. +1

**Pull request merged**
