### PR TITLE
Change repl member access modifiers for Zeppelin scalding interpreter

### PR DESCRIPTION
**Pull request by prasadwagle**
The Zeppelin scalding [interpreter](https://github.com/apache/incubator-zeppelin/pull/917) is used to
create notebooks and visualizations with scalding code. 

Given below is a skeleton of the code. ZeppelinScaldingShell is a subclass of BaseScaldingShell and getRepl is similar to process except that it returns a ScaldingILoop instead of calling repl.process.
    out = new ByteArrayOutputStream();
    PrintWriter printWriter = new PrintWriter(out, true);
    ScaldingILoop interpreter = ZeppelinScaldingShell.getRepl(args, printWriter);
    interpreter.createInterpreter();
    res = interpreter.intp().interpret(code);  // code is received from the web browser
    output = out.toString();  // this is sent to the web browser

The ZeppelinScaldingShell.getRepl method needs scaldingREPL to be protected and storedHdfsMode to be public.

### CODE REVIEW

**Comment by johnynek** [comment]
Thanks! Would love to see a blog post on using Zepplin with scalding.

**Comment by sriramkrishnan** [comment]
Not quite a blog post, but not sure if you have seen this - https://zeppelin.incubator.apache.org/docs/0.5.6-incubating/interpreter/scalding.html

**Comment by prasadwagle** [comment]
The zeppelin pull request was merged this morning. I put together a draft blog post -https://medium.com/@prasadwagle/apache-zeppelin-scalding-interpreter-ae3f749a32e3#.pqsvmk4nd. Can you please send me your feedback?

**Comment by gerashegalov** [comment]
> “-libjars directory/:directory/”
> Did you mean a sequence of directories directory1, directory2?

Note that libjars is a comma-separated list of globs. A single-file-path glob file is resolved to itself. A single directory path is equivalent to the glob directory/*

**Pull request merged**
