### PR TITLE
Bump cascading3 version to pick up hashJoin distcache update

### PR DESCRIPTION
**Pull request by piyushnarang**
Updating the Cascading3 version to the latest one which includes fix proposed in this PR: https://github.com/cwensel/cascading/pull/55. Verified that this version tackles the issue of trying to run a hashJoin job with a lot of mappers (20K+). 

Kicked off a run of our internal E2E tests with this version as well (shall write in when it's done).

### CODE REVIEW

**Comment by johnynek** [comment]
This seems to hit a new issue with cascading:

```
[info] - should merge and write to two sinks with forceToDisk *** FAILED ***
[info]   cascading.flow.planner.PlannerException: union of steps have 1 fewer elements than parent assembly: MapReduceHadoopRuleRegistry, missing: [Each(_pipe_4+_pipe_5)[Identity[decl:'id', 'count']]]
[info]   at cascading.flow.planner.FlowPlanner.verifyResultInternal(FlowPlanner.java:621)
[info]   at cascading.flow.planner.FlowPlanner.verifyResult(FlowPlanner.java:560)
[info]   at cascading.flow.planner.rule.RuleSetExec.execPlannerFor(RuleSetExec.java:163)
[info]   at cascading.flow.planner.rule.RuleSetExec$3.call(RuleSetExec.java:336)
[info]   at cascading.flow.planner.rule.RuleSetExec$3.call(RuleSetExec.java:328)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:262)
[info]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:262)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[info]   at java.lang.Thread.run(Thread.java:745)
```

Not sure if this is a direct consequence of the changes we need. I have not looked at the test in question yet (there are two, and seem to use Checkpoint/forceToDisk).

/cc @cwensel

**Comment by piyushnarang** [comment]
@johnynek yes, I noticed these failures with the E2E run as well. 
Seems like this was fixed in commit: https://github.com/cwensel/cascading/commit/4a94e5512f9b1b9f906f9d19dead78eca7d10857
That seems to be the only commit missed in 3.2-wip3: https://github.com/cwensel/cascading/compare/3.2-wip-3...wip-3.1

I tried running the tests with a branch based off:  3.2-wip3 + missing commit and that seems to have gone through. Emailed the cascading group about it as well.

**Comment by cwensel** [comment]
I've merged the newly minted 3.1.1 into wip-3.2 and the artifacts should publish in 7 hours.

https://github.com/cwensel/cascading/tree/wip-3.2

fwiw, ported commits are always reflected in this file:
https://github.com/cwensel/cascading/blob/wip-3.2/CHANGES.txt

but its rare we port commits from one prior wip to a new one. usually we do a .x release to a wip.

**Comment by piyushnarang** [comment]
Thanks @cwensel, I'll try out the latest release in our E2E tests and Scalding tests to verify things on our end.

**Comment by piyushnarang** [comment]
Looking into the platform test failures. Seems like our internal E2E tests went through though.

**Comment by piyushnarang** [comment]
Trying to figure this out. Seems like we've got a couple of failures both of which seem to be related to the hashJoin distCache update. Both sets of scenarios seem to work when I turn off the [ENABLE_DECORATE_ACCUMULATED_TAP](https://github.com/cwensel/cascading/commit/b5bc55df8e1bd285c467cbcc60cf68dceb29758c#diff-0774c458e61fb702ccb35487ecdab2c8R47) property for the given test. Not sure if the dist cache tap isn't meant to be used in the pseudo-distributed mode?

1) [merge and joinWithTiny shouldn't duplicate data](https://github.com/twitter/scalding/blob/develop/scalding-hadoop-test/src/test/scala/com/twitter/scalding/platform/PlatformTest.scala#L458) seems to report mismatching received / expected results.
2) Some of the other hashJoin tests fail with an error:

```
2016-09-12 16:03:36,993 INFO [uber-SubtaskRunner] cascading.flow.hadoop.FlowMapper: sourcing from: DistCacheTap<TempHfs["SequenceFile[[0]]"][5493232807/IterableSource(List((1,fi/]>
2016-09-12 16:03:36,993 INFO [uber-SubtaskRunner] cascading.flow.hadoop.FlowMapper: sinking to: Hfs["TextDelimited[[0:1]]"]["output"]
2016-09-12 16:03:36,994 INFO [uber-SubtaskRunner] cascading.flow.hadoop.FlowMapper: flow node id: EE156876BD7942CE83EF9BE6B1E852C8, mem on start (mb), free: 334, total: 412, max: 910
2016-09-12 16:03:37,008 INFO [uber-SubtaskRunner] cascading.tuple.collect.SpillableTupleList: attempting to load codec: org.apache.hadoop.io.compress.GzipCodec
2016-09-12 16:03:37,010 INFO [uber-SubtaskRunner] cascading.tuple.collect.SpillableTupleList: found codec: org.apache.hadoop.io.compress.GzipCodec
2016-09-12 16:03:37,042 ERROR [uber-SubtaskRunner] cascading.flow.stream.element.SourceStage: caught throwable
org.apache.hadoop.mapred.InvalidInputException: Input path does not exist: hdfs://localhost:61837/db11eaee-d712-46eb-950d-55946098305a
        at org.apache.hadoop.mapred.FileInputFormat.singleThreadedListStatus(FileInputFormat.java:285)
        at org.apache.hadoop.mapred.FileInputFormat.listStatus(FileInputFormat.java:228)
        at org.apache.hadoop.mapred.SequenceFileInputFormat.listStatus(SequenceFileInputFormat.java:45)
        at org.apache.hadoop.mapred.FileInputFormat.getSplits(FileInputFormat.java:313)
        at cascading.tap.hadoop.io.MultiRecordReaderIterator.initialize(MultiRecordReaderIterator.java:108)
        at cascading.tap.hadoop.io.MultiRecordReaderIterator.<init>(MultiRecordReaderIterator.java:84)
        at cascading.tap.hadoop.io.HadoopTupleEntrySchemeIterator.makeIterator(HadoopTupleEntrySchemeIterator.java:57)
        at cascading.tap.hadoop.io.HadoopTupleEntrySchemeIterator.<init>(HadoopTupleEntrySchemeIterator.java:44)
        at cascading.tap.hadoop.Hfs.openForRead(Hfs.java:456)
        at cascading.tap.hadoop.Hfs.openForRead(Hfs.java:109)
        at cascading.tap.DecoratorTap.openForRead(DecoratorTap.java:155)
        at cascading.tap.hadoop.BaseDistCacheTap.openForRead(BaseDistCacheTap.java:92)
...
```

**Comment by gerashegalov** [comment]
The stack trace resembles https://issues.apache.org/jira/browse/MAPREDUCE-6095 I fixed in Hadoop 2.6. You can check if moving to 2.6+ helps.

**Comment by piyushnarang** [comment]
Thanks @gerashegalov. Let me look into that.

**Comment by piyushnarang** [comment]
@gerashegalov thanks that seems to have been the issue. I bumped hadoop to 2.6.0 and tried running the failing tests and they seem to succeed now :-)

**Comment by piyushnarang** [comment]
@johnynek - green now :-). Our internal E2E tests were successful with this Cascading version as well.

**Comment by gerashegalov** [comment]
Is it necessary to track the hadoop dependency explicitly in Scalding, can we consume it transitively via cascading-hadoop?

**Comment by piyushnarang** [comment]
@gerashegalov yeah I'm not sure why Scalding explicitly lists out the hadoop dep (instead of pulling it in via cascading). Might have been to keep them decoupled for some reason. Maybe someone else has the context?

**Comment by johnynek** [comment]
we really don't like transitively pulling things we depend on. We want to declare the versions we need. Cascading itself works on many hadoop versions so it does not require a very new version, in theory.

In practice, it would seem it does require a somewhat new version.

**Comment by piyushnarang** [comment]
So basically for these tests to work we need a hadoop version above 2.6.0 (I tested that and 2.7.2). I put in 2.7.2 as thats newer and what cascading lists.

**Comment by gerashegalov** [comment]
In this case, non-committer 🚢 .

**Comment by johnynek** [comment]
Wait, will 2.6.0 work? That's what we are running. I'd hate to start
requiring cutting edge Hadoop to avoid a correctness bug.

This is worrying. If you upgrade scalding but not your Hadoop your jobs are
just silently wrong. Sounds scary.

**Comment by piyushnarang** [comment]
@johnynek - 2.6.0 will work. We were on 2.5.0 (prior to Gera's fix which was part of 2.6.0). If you want I can switch to 2.6.0

**Comment by johnynek** [comment]
👍 

Okay, I guess this bug was only in the local mode, not on the cluster, so I guess it is not as risky as I worried about.

**Pull request merged**
