### PR TITLE
Create COMMITTERS.md

### PR DESCRIPTION
**Pull request by isnotinvain**
per https://github.com/twitter/analytics-infra-governance

### CODE REVIEW

**Comment by johnynek** [comment]
can we add a link in the README about this? No one is likely to check that file.

**Comment by ulyssepence** [comment]
+1

**Comment by azymnis** [comment]
I should probably add myself to emeritus...

**Comment by isnotinvain** [comment]
@azymnis that would be great! You're still listed under Authors as well, I haven't tackled the Authors lists yet. For those, probably the actual original authors (like you) should be emeritus, and the contributors can just be in the contributors graph page.

For this first pass we just wanted to get the active committers (+1-ers) listed.

**Pull request merged**
