### PR TITLE
Ianoc/revert changes around making file systems

### PR DESCRIPTION
**Pull request by ianoc**
It turns out doing newInstance here is super expensive. It creates new hadoop configurations/reads lots of XML and does the huge hadoop-hard-to-comprehend workload.

### CODE REVIEW

**Comment by johnynek** [comment]
Merge when green.

On Thursday, July 16, 2015, ianoc <notifications@github.com> wrote:

> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/twitter/scalding/pull/1372
> Commit Summary
>
>    - Needed to revert this to 0.15.0 version and before, newInstance
>    builds new hadoop configurations and is really really slow it seems
>    - fix bad merge change
>
> File Changes
>
>    - *M*
>    scalding-core/src/main/scala/com/twitter/scalding/FileSource.scala
>    <https://github.com/twitter/scalding/pull/1372/files#diff-0> (15)
>
> Patch Links:
>
>    - https://github.com/twitter/scalding/pull/1372.patch
>    - https://github.com/twitter/scalding/pull/1372.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twitter/scalding/pull/1372>.
>


-- 
Oscar Boykin :: @posco :: http://twitter.com/posco

**Comment by isnotinvain** [comment]
What was the motivation for creating a new instance?
Is this code supposed to be thread safe? You could use a thread-local FileSystem.
I think FileSystem.get() is cached + synchronized, but I don't think the fs instances it returns are themselves thread safe.

**Comment by ianoc** [comment]
We had intermittent issues around the file systems when executions were starting in multiple threads at once. So each one should remain thread local after we get it....

**Comment by isnotinvain** [comment]
So this probably doesn't fix the (intermittent) issue then? I *think* (not sure) that path.getFileSystem() will return a shared instance when 2 instances ask for it (though it'll synchronize the setup of that instance)

**Comment by ianoc** [comment]
No it doesn't fix that, but the 'fix' here was much worse than the problem... so back to having the problem really

**Comment by isnotinvain** [comment]
right makes sense thanks

**Pull request merged**
