### PR TITLE
Add monoid and semigroup for Execution

### PR DESCRIPTION
**Pull request by johnynek**
Just added for completeness. Probably only real application is:

```Monoid.sum(actionList: List[Execution[Unit]]): Execution[Unit]```

which can be nice to combine a bunch of independent execution jobs into one.

### CODE REVIEW

**Comment by Gabriel439** [comment]
Yay!  I love this!

+1

**Comment by jnievelt** [comment]
If it'll be used to sum, should we add sumOption which uses Execution.sequence?

**Comment by johnynek** [comment]
I thought about that, but that would force us to materialize an Iterator of these into a Sequence, just to get the sumOption. It's not clear that is always a win. Instead, this is incremental and less code.

If you prefer, I can do it, but given that Execution is generally VERY slow code (it talks to the cluster in the interesting cases), I thought it was better to default to the smaller memory case.

**Comment by johnynek** [comment]
@jnievelt let me know either way.

**Comment by jnievelt** [comment]
@johnynek sure sgtm, can always add it later

**Pull request merged**
