### PR TITLE
Give good equality to TupleConversion classes

### LINKED ISSUE #1739: Remove identity TypedPipe converter + identity + setter operations.
We can do this if we give single and double arity converters and setters good equality. This can avoid some boxing.

### PR DESCRIPTION
**Pull request by johnynek**
closes #1739 

This changes the generated tuple conversion code to be case classes. This gives us nice toString, but more importantly it makes it safe to skip some `.mapTo` operations in the CascadingBackend that are only reformatting the tuple.

There may be slightly more room for optimization, but this should be an improvement all around.

### CODE REVIEW

**Comment by johnynek** [comment]
ptal @piyushnarang

**Comment by ianoc** [comment]
looks great to me, even just to have better equality and toString are good reasons for the change. Perf optimization is nice too ofc.

lgtm

**Comment by piyushnarang** [comment]
Not super familiar with this part of the code but from what I understand, looks good to me 👍

**Comment by johnynek** [comment]
Thanks for the review folks!

**Pull request merged**
