### PR TITLE
Bump spark version

### PR DESCRIPTION
**Pull request by ttim**
Currently releasing of scalding is broken for `scalding-spark` module for Scala 2.12. There are two solutions: either do not release this module for 2.12 or to bump spark version to one which is 2.12 compatible.

In this PR I've bumped spark version to 2.4.

### CODE REVIEW

**Comment by dieu** [comment]
could you enable `scalding-spark` in `.travis.yml` for 2.12.x, please?

**Comment by johnynek** [comment]
+1 to make sure we are running the spark tests in travis.

**Comment by ttim** [comment]
@dieu @johnynek Done

**Review by johnynek — APPROVED** [review]
thanks!

**Review by dieu — APPROVED** [review]

**Pull request merged**
