### PR TITLE
Moving the repl in wonderland to a dedicated md file

### PR DESCRIPTION
**Pull request by piyushnarang**
Haven't changed the content apart from adding some instructions to compile and run. (Verified that the tutorial still works)

### CODE REVIEW

**Comment by ulyssepence** [comment]
+1

**Comment by johnynek** [comment]
Can we not put it in the root? Can we have a `/doc` directory or something?

Also, it would be nice to look into tut for this:
https://github.com/tpolecat/tut

so we can be sure it compiles.

**Comment by piyushnarang** [comment]
@johnynek, sure can look into moving this into a doc dir + hooking up with tut.

**Comment by piyushnarang** [comment]
@johnynek moved this under the tutorial directory. I tried hooking up with tut but ran into some issues getting it to pick up deps and such. If it's ok, we could get this change in and once we've got tut hooked up in algebird (https://github.com/twitter/algebird/pull/556), make a similar docs update here as well?

**Comment by sritchie-stripe** [comment]
@piyushnarang I'm picking up the tut change today, so should have an update within a week!

**Comment by piyushnarang** [comment]
Thanks @sritchie. Shall keep an eye out for that :-)

**Comment by sritchie** [comment]
@piyushnarang I've finally managed to hit an open source deadline... this is all finished today, not within a week :) 

Here's the new site: https://twitter.github.io/algebird/

The whole conversion to `tut` was really easy. `repl.md` is probably the best place to look; I was able to copy over a file from the wiki, remove the `scala>` prefixes from lines and the generated output. So solid.

**Comment by piyushnarang** [comment]
hey @sritchie that's great! I'll take a look at that and try and set up some of that here too. I'm probably not going to be able to get to a full site and stuff right now, but I'd like to set up the basic tut tutorial compile checking to start off with.

**Comment by johnynek** [comment]
Let's add tut when we can.

**Comment by piyushnarang** [comment]
Thanks @johnynek. Will try to get to the tut stuff soon. Got pulled into a few file source issues..

**Pull request merged**
