### PR TITLE
Replace procedure syntax with method

### PR DESCRIPTION
**Pull request by qilab**
In this PR,
- procedure syntax is replaced with method because procedure syntax is deprecated
- side-effecting nullary methods are replaced with non-nullary ones (related PR: #1561 )

### CODE REVIEW

**Comment by jnievelt** [comment]
+1 thanks for grabbing the rest of the nullary methods.  I'd also thought about the methods change for that PR but felt it was too noisy

**Comment by johnynek** [comment]
This is great, but you need to merge with develop now (unfortunately the last merge created a conflict).

If you can merge develop we can merge this, thanks!

**Comment by qilab** [comment]
I merged develop branch (`git rebase develop`)!
I also pushed an additional commit ac8ba55f38956f97e6588b502787190ecfc6f783.

**Comment by johnynek** [comment]
Thanks for the PR! More (source compatible) cleanups welcome!

**Pull request merged**
