### PR TITLE
Upgrade to sbt 1.3.10

### PR DESCRIPTION
**Pull request by Duhemm**
This is an attempt at fixing the build. Cleaning Travis' cache may be required as well.

It looks like Maven central now serves artifacts only over HTTPS anyway.

-----

It turns out that the above fix was not enough to get a green build -- I'm trying to upgrade to latest sbt.

### CODE REVIEW

**Comment by Duhemm** [comment]
It looks like the first commit helped, even without clearing the cache. There are still some downloads that failed from maven (though for me they worked fine 🤔

I updated to latest sbt 0.13 in the second commit; let's see what happens.

**Comment by Duhemm** [comment]
Strange:

```
:::: WARNINGS
	problem while downloading module descriptor: https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.10.7/scala-reflect-2.10.7.pom: The HTTP response code for https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.10.7/scala-reflect-2.10.7.pom did not indicate a success. See log for more detail. (42ms)
```

That URL works fine on my machine. Is Travis having issues? Some of the builds are green at least.

**Comment by johnynek** [comment]
I tried to restart the builds... I think there could be a caching thing that isn't working here. I think there may be a corrupted travis cache.

Also, it might be worth updating to sbt 1.3.9 or something soon. It is a bummer this is such a pain...

Maybe we should turn on scala steward to update the repo when dependencies change so at least the CI is running more often.

**Comment by Duhemm** [comment]
I just tried upgrading to sbt 1.3.10. This should be the minimal diff (to `build.sbt`...) required to get the build to work with sbt 1.3.10.

I had to upgrade scalariform, which reformatted everything. I'm not sure how to get the same formatting as before. If you don't want the formatting changes, it'd be nice if someone could figure out how to configure it back. This branch should be writable to maintainers of this repo 😄

**Comment by johnynek** [comment]
looks like the ci failed...

I'd rather disable and remove scalariform honestly and not have the code change since this is already big. the community has moved to scalafmt, so we should set that up if we want modern formatting (but we can do that in a separate PR).

Thanks for working on this!

**Comment by johnynek** [comment]
question: can you try these locally rather than using travis (which is pretty slow on turn around)?

I filed #1929 as it looks like at least one of these errors is a flakey test.

**Comment by Duhemm** [comment]
Sure, I just didn't want to try everything on my machine (I'm mostly doing that when I'm waiting for something else).

Thanks for filing the issue. This test does pass on my machine.

Hopefully we shouldn't be too far from a green build now 🤞

**Comment by Duhemm** [comment]
Everything should pass (given a clean cache at least) with this last commit. At least, it's working on my machine 😄 and I hope here as well: https://travis-ci.org/github/Duhemm/scalding/builds/684050063

**Comment by johnynek** [comment]
looks like the repl CI tests are failing probably due to how the new sbt processes CLI args:

https://travis-ci.org/github/twitter/scalding/jobs/684050109#L1297

man, this CI is brutal...

**Comment by johnynek** [comment]
Can you merge develop to get #1930?

**Comment by ttim** [comment]
I’ll take a look on this PR and try to get it working today.

**Comment by tlazaro** [comment]
Seems solved by #1939, should we close this?

**Comment by Duhemm** [comment]
Thanks @ttim for taking over, and @tlazaro for reminding me!

**Pull request closed without merging**
