### PR TITLE
Add DateRange.prepend (opposite direction of extend)

### PR DESCRIPTION
**Pull request by FlavSF**

### CODE REVIEW

**Comment by johnynek** [comment]
Looks good to me, but we are trying to increase test coverage. Can we add a test?

**Comment by isnotinvain** [comment]
@FlavSF looks like https://github.com/twitter/scalding/blob/develop/scalding-date/src/test/scala/com/twitter/scalding/DateTest.scala is probably the right place to add the test

**Comment by FlavSF** [comment]
Thanks both. I started working on unit tests but I'm facing some laptop issues. Give me a few days and I'll get it done.

**Review by johnynek — APPROVED** [review]
Thank you sir!

**Pull request merged**
