### PR TITLE
Update Scala version to 2.10.6

### PR DESCRIPTION
**Pull request by zaneli**

### CODE REVIEW

**Comment by benpence** [comment]
Would you please talk about why you updated scala? It's not clear from your commit.

**Comment by zaneli** [comment]
Sorry, there is no clear reason in this...
but generally, I'd like to keep the latest version as much as possible.

I guess https://github.com/twitter/scalding/commit/512eca502069c928c30a29ace4739bb3812fd1c7, https://github.com/twitter/scalding/commit/9510d5145d5099eb705d0cc18081b54a305098a7 look the similar reason.

**Comment by johnynek** [comment]
Seems fine to me. This does not change the dependencies (since scala publishes with `_2.10` so it should be binary compatible).

**Comment by zaneli** [comment]
Thank you!

**Pull request merged**
